// ======================================================================
// Project Name    : android_renderer
//
// Copyright © 2020 U-CREATES. All rights reserved.
//
// This source code is the property of U-CREATES.
// If such findings are accepted at any time.
// We hope the tips and helpful in developing.
// ======================================================================
package com.ucreates.renderer.asset.mesh;
import android.opengl.GLES11;
import com.ucreates.renderer.asset.BaseAsset;
import com.ucreates.renderer.entity.GLESColor;
import com.ucreates.renderer.entity.VertexArray;
public class CubeAsset1 extends BaseAsset {
    public CubeAsset1(float width, float height, float depth, GLESColor color) {
        this.width = width;
        this.height = height;
        this.depth = depth;
        this.color = color;
        this.renderMode = GLES11.GL_TRIANGLES;
        this.vertex = new VertexArray(3);
    }
    @Override
    public void create() {
        float verticies[] = {
            // front1
            -0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            // front2
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            // back1
            -0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            // back2
            0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            // right1
            0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            // right2
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            // left1
            -0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            -0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            // left2
            -0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            // top1
            -0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            // top2
            0.5f * this.width,
            0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            0.5f * this.width,
            0.5f * this.height,
            0.5f * this.depth,
            // bottom1
            -0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            // bottom2
            0.5f * this.width,
            -0.5f * this.height,
            -0.5f * this.depth,
            0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
            -0.5f * this.width,
            -0.5f * this.height,
            0.5f * this.depth,
        };
        float vertexColors[] = {
            // front
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            // back
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            // left
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            // right
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            // top
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            // bottom
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
            this.color.r,
            this.color.g,
            this.color.b,
            this.color.a,
        };
        int vertexCount = verticies.length / this.vertex.dimension;
        this.vertex.setVertexCount(vertexCount);
        this.vertex.setVertices(verticies);
        this.vertex.setColors(vertexColors);
        this.vertex.setNormals(verticies);
        return;
    }
}
